db:
  container_name: pg_container
  image: postgres
  restart: always
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: Root@123Root
    POSTGRES_DB: tennis_db
  ports:
    - "5432:5432"
pgadmin:
  container_name: pgadmin4_container
  image: dpage/pgadmin4
  restart: always
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: root
  links:
    - db
  ports:
    - "5050:80"
